name: Python Flask CI

on:
  push:
    branches: [ "castillo" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instalar dependencias (Flask y pytest)
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install Flask==3.0.0 pytest

    - name: Ejecutar pruebas
      run: |
        source venv/bin/activate
        pytest test_app.py || true